### ISSUE TITLE
Readphaser

### ISSUE THREAD

**Issue by ratanchopra** [vsbuffalo/readphaser#1]
Hi there,

I came across this tool in the provisional pdf of Krasileva et. al., and seems very interesting way of addressing the homeolog separation issue. I tried to download the readphaser scripts and I did not obtain the fasta files using pr.py command. Are there any pre-requisites for the program to be run? Although I could not compile fermi assembler in python because of missing library libfermi.so but I did not see any code for the fermi in pr.py. I would really appreciate if your time allows to comment on this post.

Thanks
Ratan Chopra

**Comment by vsbuffalo** [comment]
Readphaser takes BAM files and the output from HapCut. There was a bug in fermi, so we used Mira (details in paper). We ran readphaser so that it would output phased reads, which were separated by another script and assembled in sets. Hope this helps!

**Comment by ratanchopra** [comment]
Okay Thanks for your quick reply.
