### ISSUE TITLE
error while running readphaser

### ISSUE THREAD

**Issue by joqb** [vsbuffalo/readphaser#4]
Hi,

I'm trying to get to get readphaser running. For the moment I'm experiencing on the HAPCUT test data.
here is the error I got:

-bash-4.2$ pr.py NA18508.chr20.test.bam.hapcut NA18508.chr20.test.bam
[phase_reads] opening alignment BAM file... done.
[phase_reads] phasing '20', block_id 0
Traceback (most recent call last):
  File "/opt/Bio/readphaser/20150325/bin/pr.py", line 365, in <module>
    output_main(args)
  File "/opt/Bio/readphaser/20150325/bin/pr.py", line 335, in output_main
    region=args.region)
  File "/opt/Bio/readphaser/20150325/bin/pr.py", line 298, in phase_reads
    group_reads_by_block(reads, block, block_id, callback, stats, inconsistent_counts_file)
  File "/opt/Bio/readphaser/20150325/bin/pr.py", line 212, in group_reads_by_block
    htype_pos = group_varpos_by_haplotype(readpair, haplotypes, allele_counts)
  File "/opt/Bio/readphaser/20150325/bin/pr.py", line 147, in group_varpos_by_haplotype
    if read.overlap(interval[0], interval[1]) == allele_len:
TypeError: overlap() takes no arguments (2 given)

Cheers,
Nath

**Comment by iamcorrinne** [comment]
I get the same errors.  Have you figured out a solution?

Thanks,
Corrinne

**Comment by vsbuffalo** [comment]
Could you provide the test data somewhere? What version of Python are you using?

**Comment by iamcorrinne** [comment]
I am running Python 2.7.9 on Red Hat 4.8.2-16.  I have sent a link to your gmail account to download a file.  (It contains the hapcut output and the corresponding bam). Is that okay?

Thanks!

**Comment by vsbuffalo** [comment]
@iamcorrinne can you paste your exact error?

**Comment by vsbuffalo** [comment]
@iamcorrinne Can you verify your hapcut file? I noticed something rather strange (though admittedly, I haven't looked at HapCut files in more than a year, so I may be overlooking something): 

```
3091    2       0       161_Gorai.012G146100.2_ 1684    T       G,A     0/2:175,255,255,0,255,255       94,0:-317.4,-333.3,-667.3:15.8:4.0:FV
```

The format according to [the HapCut documentation](https://github.com/vibansal/hapcut) is:

```
variant_id
haplotype_1
haplotype_2
chromosome
position
refallele
variantallele
genotype
allele_counts:genotype_likelihoods:delta:MEC_variant
```

Where "Haplotype_1 and Haplotype_2 correspond to the two phased haplotypes (0 corresponds to the refallele and 1 corresponds to the variantallele)". But in the example line from your file, I see 2s in there, which is causing an IndexError exception. This might be an upstream bug in HapCut. Could you take a look at this, and possibly verify with @vibansal?

**Comment by iamcorrinne** [comment]
Weird.  Sure, I will rerun the program and look at the output and then go from there.  For your reference, this is the error:

[corrinne@biocrunch test]$ python pr.py 165_S2.hapcut 165_S2.sort.bam
[phase_reads] opening alignment BAM file...     done.
[phase_reads] phasing '209_Gorai.003G109000.1_', block_id 0
Traceback (most recent call last):
  File "pr.py", line 364, in <module>
    output_main(args)
  File "pr.py", line 334, in output_main
    region=args.region)
  File "pr.py", line 297, in phase_reads
    group_reads_by_block(reads, block, block_id, callback, stats, inconsistent_counts_file)
  File "pr.py", line 211, in group_reads_by_block
    htype_pos = group_varpos_by_haplotype(readpair, haplotypes, allele_counts)
  File "pr.py", line 146, in group_varpos_by_haplotype
    if read.overlap(interval[0], interval[1]) == allele_len:
TypeError: overlap() takes no arguments (2 given)

Thanks!

**Comment by vsbuffalo** [comment]
More info (sorry for the stream of consciousness here) — so when I try to replicate on your data, I get a different error than the original posted here:

```
[phase_reads] phasing '11603_Gorai.005G183400.2_', block_id 0
Traceback (most recent call last):
File "pr.py", line 364, in <module>
output_main(args)
File "pr.py", line 334, in output_main
region=args.region)
File "pr.py", line 297, in phase_reads
group_reads_by_block(reads, block, block_id, callback, stats, inconsistent_counts_file)
File "pr.py", line 243, in group_reads_by_block
phased_readsets[phase].add_readpair(readpair)
IndexError: tuple index out of range
```

Investigating, I find twos in columns 2 and 3 (when they shouldn't be there). So, then, removing them with a quick awk hack (this isn't the best approach, but for testing works):

```
$ awk '{if ($2 == 2 || $2 == 2) {} else {print $0}}' ../data/165_S2.hapcut  > test.hapcut
$ python pr.py test.hapcut  ../data/165_S2.sort.bam
```

Everything seems to work fine.

**Comment by vsbuffalo** [comment]
Interesting! different error than the one I was having. Can you try that awk oneliner and then run `pr.py` on that `test.hapcut` file? Do you still get the error?

**Comment by iamcorrinne** [comment]
Yeah, I did and I do!  

[corrinne@biocrunch test]$ python pr.py test.hapcut 165_S2.sort.bam
[phase_reads] opening alignment BAM file...     done.
[phase_reads] phasing '209_Gorai.003G109000.1_', block_id 0
Traceback (most recent call last):
  File "pr.py", line 364, in <module>
    output_main(args)
  File "pr.py", line 334, in output_main
    region=args.region)
  File "pr.py", line 297, in phase_reads
    group_reads_by_block(reads, block, block_id, callback, stats, inconsistent_counts_file)
  File "pr.py", line 211, in group_reads_by_block
    htype_pos = group_varpos_by_haplotype(readpair, haplotypes, allele_counts)
  File "pr.py", line 146, in group_varpos_by_haplotype
    if read.overlap(interval[0], interval[1]) == allele_len:
TypeError: overlap() takes no arguments (2 given)

**Comment by iamcorrinne** [comment]
To be certain, you are using the same version of pr.py that is posted here?  Could there be an update to a module that is breaking it?  This is a new system that we are running on, so the admins are installing the latest stuff.

**Comment by vsbuffalo** [comment]
Let's check — 

```
>>> import pysam
>>> pysam.__version__
```

   '0.8.1'

Do you get the same thing?

**Comment by iamcorrinne** [comment]
Nope.  

> > > import pysam
> > > pysam.**version**
> > > '0.8.2.1'

**Comment by vsbuffalo** [comment]
Cool — will update on my side and get back in a bit.

**Comment by iamcorrinne** [comment]
Thanks!

**Comment by vsbuffalo** [comment]
Hi @iamcorrinne — that was the issue, pysam updated its `AlignedSegment.overlap()` method to `AlignedSegments.get_overlap()`. f5e3152af8cb79a5d59cafe8db51c8c1e6120f1d solves this issue — please let me know if this doesn't work! If it does, I can close the issue.

**Comment by iamcorrinne** [comment]
Thanks @vsbuffalo, it seems to work. It output fastq files for both phased and unphased contigs.  Now I only have to track down the source of those weird 2's...  

Thanks for your support!
Corrinne

**Comment by vsbuffalo** [comment]
Great, glad we solved it. Thanks so much for helping me figure out the issue!

**Comment by vibansal** [comment]
The '2' is present in the HapCUT output since the site has multiple variant alleles in the VCF file and the genotype of the individual is 0/2. This implies that the second variant allele (encoded as 2) is present on one haplotype.

**Comment by vsbuffalo** [comment]
Terrific, thanks @vibansal! @iamcorrinne in this case I'd recommend filtering the VCF so only biallelic loci are kept. I can add a warning to readphaser.

**Comment by iamcorrinne** [comment]
Thanks @vibansal @vsbuffalo!  This may be due to the fact that I don't have a good reference for this species (I should have run the first test with a better sample), but it could also be a cryptic polyploid with multiple homoeologs mapping to the same locus.  Thanks for your help!
